kind: Deployment
apiVersion: apps/v1
metadata:
  name: 2048-deployment
  labels:
    app: 2048-game
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: 2048-game
  template:
    metadata:
      labels:
        app: 2048-game
    spec:
      containers:
      - name: 2048-game
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.containerPort }}
