kind: Deployment
apiVersion: apps/v1
metadata:
  name: doom-deployment
  labels:
    app: doom
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: doom
  template:
    metadata:
      labels:
        app: doom
    spec:
      containers:
      - name: doom
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.containerPort }}
        env:
        - name: VNC_PW
          value: {{ .Values.vnc.password }}

